# Generated by Django 4.0.3 on 2022-08-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('asignaturas', '0002_remove_asignatura_id_profesor_asignatura_profesor'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='id_estudiante',
        ),
        migrations.AddField(
            model_name='clase',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura'),
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
    ]
