# Generated by Django 4.0.3 on 2022-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('numIdentificacion', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=30)),
            ],
        ),
    ]
